name: "CI All"
inputs: {}
runs:
  using: "composite"
  steps:
    - name: "Check Jobs"
      shell: "sh"
      run: |
        results=$(grep '"result":' <<<'${{ toJson(needs) }}')
        if grep -vq success <<<"$results"; then
          echo "One or more unsuccessful jobs" >&2
          exit 1
        fi
        echo "All jobs passed"
