name: "Setup"
inputs: {}
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      shell: "/bin/bash"
      env:
        SERVER: "${{ github.server_url }}"
      run: |
        proto="${SERVER%%://*}"
        host="${SERVER#*://}"
        git clone "${proto}://oauth2:${{ github.token }}@${host}/${{ github.repository }}" .
        git -c advice.detachedHead=false checkout ${{ github.sha }}

    - name: "Copy Task Binary"
      shell: "/bin/bash"
      run:  |
        tar -x -C /usr/local/bin --no-same-owner -f "${{ github.action_path }}/task_linux_amd64.tar.gz" task
