name: "Setup"
inputs: {}
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      env:
        SERVER: "${{ github.server_url }}"
      run: |
        proto="${SERVER%%://*}"
        host="${SERVER#*://}"
        git clone "${proto}://oauth2:${{ github.token }}@${host}/${{ github.repository }}" .
        git checkout ${{ github.sha }}

    - name: "Copy Task Binary"
      run:  |
        tar xf -C /usr/local/bin "${{ github.action_path }}/task_linux_amd64.tar.gz" task
